Change indentation

diff --git a/bin/nomis-lein-all b/bin/nomis-lein-all
--- a/bin/nomis-lein-all
+++ b/bin/nomis-lein-all
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash -e
 
 if [ "$1" = "" ]; then
-  echo "Missing command, e.g check or midje"
-  exit 1
+    echo "Missing command, e.g check or midje"
+    exit 1
 fi
 
 for x in *
 do
-  if [ -d "$x" ] && [ "$x" != "nomis-emacs-configuration" ]; then
-    echo "==== $x ===="
-    cd "$x"
-    lein $1 || true
-    cd ..
-  fi
+    if [ -d "$x" ] && [ "$x" != "nomis-emacs-configuration" ]; then
+        echo "==== $x ===="
+        cd "$x"
+        lein $1 || true
+        cd ..
+    fi
 done
 
 bells
